# Learning pytorch

In [1]:
import torch

## Broadcasting
Two tensors are "broadcastable" if the following rules hold:

- Each tensor has at least one dimension.

- When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

In [34]:
x = torch.arange(0,4).view(2,2)
y = torch.arange(5,7).view((2))
print(x)
print(y)
print()
print(y-x)

tensor([[0, 1],
        [2, 3]])
tensor([5, 6])

tensor([[5, 5],
        [3, 3]])
